/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'
import * as THREE from 'three'

export function Model(props) {
  const { nodes, materials } = useGLTF('/iphone17promax.glb')
  
  // 1. Загружаем текстуру для экрана
  // Убедись, что файл wallpaper.jpg лежит в папке public!
  const screenTexture = useTexture('/wallpaper.jpg')
  screenTexture.flipY = false // Иногда текстуры перевернуты, это исправляет

  useEffect(() => {
    // Цвет, который выбрал юзер
    const userColor = new THREE.Color(props.itemColor)

    // --- ЗОНА ЭКСПЕРИМЕНТОВ ---
    
    // СЮДА мы впишем имя материала корпуса, когда найдем его кликом.
    // Например: materials.КорпусНазвание
    
    // СЮДА мы впишем имя материала экрана.
    // Например: materials.ЭкранНазвание

  }, [props.itemColor, materials])

  // Функция-детектор
  const handlePartClick = (e, name, materialName) => {
    e.stopPropagation()
    console.log('-----------------------')
    console.log('🧊 Ты кликнул по части:', name)
    console.log('🎨 Имя материала:', materialName)
    console.log('-----------------------')
    
    // Визуальная подсказка: мигнет красным
    e.object.material.color.set('red')
    alert(`Это материал: ${materialName}. Скопируй его имя из консоли!`)
  }

  return (
    <group {...props} dispose={null}>
      {/* Я вернул все меши, чтобы мы могли на них тыкать */}
      {Object.keys(nodes).map((key) => {
        if (nodes[key].type === 'Mesh') {
          return (
            <mesh 
              key={key}
              geometry={nodes[key].geometry}
              material={materials[nodes[key].material.name]}
              // Обрати внимание: я убрал жесткие координаты, чтобы они брались из файла
              // Но если модель "развалится", верни оригинальные пропсы из своего старого файла
              position={nodes[key].position}
              rotation={nodes[key].rotation}
              scale={nodes[key].scale}
              onClick={(e) => handlePartClick(e, key, nodes[key].material.name)}
            />
          )
        }
        return null
      })}
    </group>
  )
}

useGLTF.preload('/iphone17promax.glb')